# Generated by Django 6.0.3 on 2026-04-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_demand_7d', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_of_stock_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_reorder_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('explanation', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_recommendations', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-generated_at', 'item__item_name'],
            },
        ),
    ]
