# Generated by Django 6.0.3 on 2026-04-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_demand', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_name', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-forecast_date', 'item__item_name'],
                'unique_together': {('item', 'forecast_date', 'model_name')},
            },
        ),
    ]
