# Generated by Django 6.0.3 on 2026-04-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_item_id', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('missing_item', 'Missing Item'), ('invalid_quantity', 'Invalid Quantity'), ('invalid_date', 'Invalid Date'), ('duplicate_record', 'Duplicate Record'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('source_table', models.CharField(max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['raw_item_id'], name='consumption_raw_ite_1f67d6_idx'), models.Index(fields=['resolved'], name='consumption_resolve_f9f038_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_id', models.CharField(max_length=50, unique=True)),
                ('raw_item_id', models.CharField(max_length=100)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_consumptions', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-date', 'raw_item_id'],
                'indexes': [models.Index(fields=['date'], name='consumption_date_8c1110_idx'), models.Index(fields=['raw_item_id'], name='consumption_raw_ite_769fc9_idx')],
            },
        ),
    ]
