# name: Build and deploy Python app to Azure Web App - demandlens-api

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python version
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           cd backend
#           python -m venv antenv
#           source antenv/bin/activate
#           pip install -r requirements.txt

#       - name: Upload artifact for deployment jobs
#         uses: actions/upload-artifact@v4
#         with:
#           name: python-app
#           path: backend  

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: python-app

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
          # client-id:  ${{ secrets.AZUREAPPSERVICE_CLIENTID_6393A4BD8BF64FDE879FA4A86B5F562D }}
          # tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A4ADFAC6D76488BAEEBD48A4B537413 }}
          # subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3D78C4D855949D7985413F31C03FC45 }}

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'demandlens-api'
#           slot-name: 'Production'
#           package: .   # 🔥 deploy backend folder


# name: Deploy Django Backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           cd backend
#           python -m pip install --upgrade pip
#           pip install --no-cache-dir -r requirements.txt

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6393A4BD8BF64FDE879FA4A86B5F562D }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A4ADFAC6D76488BAEEBD48A4B537413 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3D78C4D855949D7985413F31C03FC45 }}

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: demandlens-api
#           slot-name: Production
#           package: backend



# name: Deploy Django Backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: |
#           cd backend
#           python -m pip install --upgrade pip
#           pip install --no-cache-dir -r requirements.txt
          

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6393A4BD8BF64FDE879FA4A86B5F562D }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A4ADFAC6D76488BAEEBD48A4B537413 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3D78C4D855949D7985413F31C03FC45 }}

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: demandlens-api
#           slot-name: Production
#           package: 



# name: Deploy Django Backend

# on:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6393A4BD8BF64FDE879FA4A86B5F562D }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A4ADFAC6D76488BAEEBD48A4B537413 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3D78C4D855949D7985413F31C03FC45 }}

#       - name: Deploy ONLY backend
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: demandlens-api
#           slot-name: Production
#           package: ./backend


name: Deploy Django Backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6393A4BD8BF64FDE879FA4A86B5F562D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A4ADFAC6D76488BAEEBD48A4B537413 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3D78C4D855949D7985413F31C03FC45 }}

      - name: Deploy Backend with Build
        uses: azure/webapps-deploy@v3
        with:
          app-name: demandlens-api
          slot-name: Production
          package: ./backend
          enable-oryx-build: true   # 🔥 THIS IS THE KEY